Proposition for fixing a devtool install error
When installing with devtools:

> devtools::install_github('dutri001/ggSpatial')
Downloading GitHub repo dutri001/ggSpatial@master
✔  checking for file ‘/tmp/Rtmpre96Uh/remotes1806dc1b30f/loicdtx-ggSpatial-008f6fa/DESCRIPTION’ ...
─  preparing ‘ggSpatial’:
✔  checking DESCRIPTION meta-information ...
   Warning in .write_description(db, ldpath) :
     Unknown encoding with non-ASCII data: converting to ASCII
   Error in iconv(x[ind], "latin1", "ASCII", sub = "byte") : 
     object 'ind' not found
   Execution halted
Error: Failed to install 'ggSpatial' from GitHub:
  System command error, exit status: 1, stdout + stderr:
E> * checking for file ‘/tmp/Rtmpre96Uh/remotes1806dc1b30f/loicdtx-ggSpatial-008f6fa/DESCRIPTION’ ... OK
E> * preparing ‘ggSpatial’:
E> * checking DESCRIPTION meta-information ... OK
E> Warning in .write_description(db, ldpath) :
E>   Unknown encoding with non-ASCII data: converting to ASCII
E> Error in iconv(x[ind], "latin1", "ASCII", sub = "byte") : 
E>   object 'ind' not found
E> Execution halted



Problem comes from the DESCRIPTION file, name "Loïc" (the ï especially) is not recognized (at least with ubuntu 14.04 and R 3.4.4).